# Generated by Django 4.1.5 on 2023-08-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiestand',
            name='hourly_sales',
            field=models.TextField(default=list, null=True),
        ),
    ]
